import TopNav from "@/components/topNav";
import "../styles/globals.css";
import { Inter, Nunito } from "next/font/google";
import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";
import FirebaseConfig from "@/services/firebase";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  FirebaseConfig.init();
  return (
    <html lang="en">
      <body className={nunito.className}>{children}</body>
    </html>
  );
}
